{% set name = "skl2onnx" %}
{% set version = "1.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skl2onnx-{{ version }}.tar.gz
  sha256: c67521bf1baf6fbed5c4b6388f88a0304edccce4647fc8c86c0d85770b03d336

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.15
    - onnx >=1.2.1
    - onnxconverter-common >=1.6.1
    - protobuf
    - scikit-learn >=0.19
    - scipy >=1.0

test:
  imports:
    - skl2onnx
    - skl2onnx.algebra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/sklearn-onnx
  summary: Convert scikit-learn models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
