{% set name = "skl2onnx" %}
{% set version = "1.8.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/sklearn-onnx/archive/{{ version }}.tar.gz
  sha256: 09dbc03a9edf581011e7f09f4dd6f5de068658b444ffcd5b93425b89b6c8f541

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six
    - numpy >=1.15
    - scipy >=1.0
    - protobuf
    - onnx >=1.2.1
    - scikit-learn >=0.19
    - onnxconverter-common >=1.6.1,<1.9

test:
  imports:
    - skl2onnx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/sklearn-onnx
  summary: Convert scikit-learn models and pipelines to ONNX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
