{% set name = "skl2onnx" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c74ea827d92ba186fe659695e8fc989cd97bfc320edce3d32b9936a5878da10a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools >=70
  run:
    - python
    - onnx >=1.2.1
    - scikit-learn >=1.1

# Skiped documentation tests
{% set deselect_tests = " --deselect=tests/test_algebra_onnx_doc.py::TestAlgebraOnnxDoc::test_doc_sklearn" %}
# E   Arrays are not almost equal to 7 decimals
{% set deselect_tests = deselect_tests + " --deselect=tests/test_sklearn_one_hot_encoder_converter.py::TestSklearnOneHotEncoderConverter::test_shape_inference_onnx" %}  # [linux and aarch64]

test:
  source_files:
    - tests
  imports:
    - skl2onnx
    - skl2onnx.algebra
    - skl2onnx.common
    - skl2onnx.helpers
    - skl2onnx.operator_converters
    - skl2onnx.proto
    - skl2onnx.shape_calculators
    - skl2onnx.sklapi
    - skl2onnx.tutorial
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - onnxruntime
    - pandas

about:
  home: https://onnx.ai/sklearn-onnx
  summary: Convert scikit-learn models to ONNX
  description: |
    sklearn-onnx converts scikit-learn models to ONNX. Once in the ONNX format, you can use tools like
    `ONNX Runtime` for high performance scoring. All converters are tested with onnxruntime.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/onnx/sklearn-onnx
  doc_url: https://onnx.ai/sklearn-onnx/api_summary.html

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch