{% set name = "skl2onnx" %}
{% set version = "1.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skl2onnx-{{ version }}.tar.gz
  sha256: 5f352f6b9b855ffac6305a707f02c7d436f4368938ee9049092a95a3565c273d

build:
  number: 0
  # trigger 1
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.15
    - onnx >=1.2.1
    - onnxconverter-common >=1.7.0
    - protobuf 
    - scikit-learn >=0.19,<=1.1.1
    - scipy >=1.0
    - packaging

test:
  imports:
    - skl2onnx
    - skl2onnx.algebra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://onnx.ai/sklearn-onnx/
  summary: Convert scikit-learn models to ONNX
  description: |
    sklearn-onnx converts scikit-learn models to ONNX. Once in the ONNX format, you can use tools like `ONNX Runtime` for high performance scoring. All converters are tested with onnxruntime.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/onnx/sklearn-onnx
  doc_url: https://onnx.ai/sklearn-onnx/api_summary.html


extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
